"""article_text_fields

Revision ID: 215548651d72
Revises: 6a5dbf632264
Create Date: 2026-06-10 23:49:07.351428

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "215548651d72"
down_revision: Union[str, Sequence[str], None] = "6a5dbf632264"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "articles",
        "url",
        existing_type=sa.VARCHAR(length=2048),
        type_=sa.String(length=4096),
        existing_nullable=False,
    )
    op.alter_column(
        "articles",
        "author",
        existing_type=sa.VARCHAR(length=256),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "articles",
        "source_name",
        existing_type=sa.VARCHAR(length=256),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "articles",
        "source_name",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=256),
        existing_nullable=True,
    )
    op.alter_column(
        "articles",
        "author",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=256),
        existing_nullable=True,
    )
    op.alter_column(
        "articles",
        "url",
        existing_type=sa.String(length=4096),
        type_=sa.VARCHAR(length=2048),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
