"""initial_schema

Revision ID: 21af7d79c2f7
Revises: 
Create Date: 2026-06-14 21:02:00.429354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21af7d79c2f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_sources',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('source_type', sa.Enum('RSS', 'API', 'SCRAPER', name='sourcetype'), nullable=False),
    sa.Column('timezone_hint', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('circuit_breaker_state', sa.Enum('CLOSED', 'OPEN', 'HALF_OPEN', name='circuitbreakerstate', native_enum=False, length=32), server_default='CLOSED', nullable=False),
    sa.Column('success_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failure_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.Column('health_score', sa.Float(), server_default='100.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feed_sources')),
    sa.UniqueConstraint('url', name=op.f('uq_feed_sources_url'))
    )
    op.create_index(op.f('ix_feed_sources_is_active'), 'feed_sources', ['is_active'], unique=False)
    op.create_index(op.f('ix_feed_sources_slug'), 'feed_sources', ['slug'], unique=True)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('articles_ingested', sa.Integer(), nullable=False),
    sa.Column('duplicates_detected', sa.Integer(), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'PARTIAL_SUCCESS', 'FAILED', name='pipelinerunstatus', native_enum=False, length=32), nullable=False),
    sa.Column('trigger_type', sa.String(length=64), server_default='MANUAL', nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('failed_sources', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_runs'))
    )
    op.create_table('articles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=4096), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='SHA-256 hex digest of normalized title + body for dedup'),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='Nullable: some RSS feeds omit pubDate. NULLs excluded from time-range queries.'),
    sa.Column('quality_score', sa.Float(), nullable=True, comment='Quality gate score 0.0-1.0'),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(summary, '') || ' ' || coalesce(body, ''))", persisted=True), nullable=True),
    sa.Column('category', sa.Enum('MARKETS', 'ECONOMY', 'CORPORATE', 'POLICY', 'COMMODITIES', 'CRYPTO', 'PERSONAL_FINANCE', 'INTERNATIONAL', 'OTHER', name='articlecategory', native_enum=False, length=32), nullable=True),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', name='sentimentlabel', native_enum=False, length=32), nullable=True),
    sa.Column('sentiment_label', sa.String(length=50), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('generated_summary', sa.Text(), nullable=True),
    sa.Column('feed_source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_source_id'], ['feed_sources.id'], name=op.f('fk_articles_feed_source_id_feed_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles'))
    )
    op.create_index('ix_articles_category', 'articles', ['category'], unique=False)
    op.create_index(op.f('ix_articles_content_hash'), 'articles', ['content_hash'], unique=True)
    op.create_index(op.f('ix_articles_published_at'), 'articles', ['published_at'], unique=False)
    op.create_index('ix_articles_published_id_desc', 'articles', [sa.literal_column('published_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_index('ix_articles_search_vector', 'articles', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_articles_source_name_published', 'articles', ['source_name', sa.literal_column('published_at DESC')], unique=False)
    op.create_index('ix_articles_source_published', 'articles', ['feed_source_id', 'published_at'], unique=False)
    op.create_index(op.f('ix_articles_url'), 'articles', ['url'], unique=True)
    op.create_table('raw_articles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('fetched_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at_raw', sa.String(length=256), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transport_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_status', sa.Enum('PENDING', 'NORMALIZED', 'FAILED', name='processingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('normalization_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name=op.f('fk_raw_articles_pipeline_run_id_pipeline_runs')),
    sa.ForeignKeyConstraint(['source_id'], ['feed_sources.id'], name=op.f('fk_raw_articles_source_id_feed_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_articles'))
    )
    op.create_index('ix_raw_articles_source_status', 'raw_articles', ['source_id', 'processing_status'], unique=False)
    op.create_table('article_entities',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('entity', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('extractor_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_entities_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_entities'))
    )
    op.create_index('ix_article_entities_article_id', 'article_entities', ['article_id'], unique=False)
    op.create_index('ix_article_entities_entity', 'article_entities', ['entity'], unique=False)
    op.create_index('ix_article_entities_type', 'article_entities', ['entity_type'], unique=False)
    op.create_index('uq_article_entities_article_entity_type', 'article_entities', ['article_id', 'entity', 'entity_type'], unique=True)
    op.create_table('article_keywords',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_keywords_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_keywords'))
    )
    op.create_index('ix_article_keywords_article_id', 'article_keywords', ['article_id'], unique=False)
    op.create_index('ix_article_keywords_keyword', 'article_keywords', ['keyword'], unique=False)
    op.create_index('uq_article_keywords_article_keyword', 'article_keywords', ['article_id', 'keyword'], unique=True)
    op.create_table('article_sectors',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_sectors_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_sectors'))
    )
    op.create_index('ix_article_sectors_article_id', 'article_sectors', ['article_id'], unique=False)
    op.create_index('ix_article_sectors_sector', 'article_sectors', ['sector'], unique=False)
    op.create_index('uq_article_sectors_article_sector', 'article_sectors', ['article_id', 'sector'], unique=True)
    op.create_table('failed_articles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('raw_article_id', sa.Uuid(), nullable=True),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('failure_stage', sa.Enum('COLLECTION', 'NORMALIZATION', 'VALIDATION', 'PERSISTENCE', name='failurestage', native_enum=False, length=32), nullable=False),
    sa.Column('error_type', sa.String(length=256), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('replayed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name=op.f('fk_failed_articles_pipeline_run_id_pipeline_runs')),
    sa.ForeignKeyConstraint(['raw_article_id'], ['raw_articles.id'], name=op.f('fk_failed_articles_raw_article_id_raw_articles')),
    sa.ForeignKeyConstraint(['source_id'], ['feed_sources.id'], name=op.f('fk_failed_articles_source_id_feed_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_failed_articles'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failed_articles')
    op.drop_index('uq_article_sectors_article_sector', table_name='article_sectors')
    op.drop_index('ix_article_sectors_sector', table_name='article_sectors')
    op.drop_index('ix_article_sectors_article_id', table_name='article_sectors')
    op.drop_table('article_sectors')
    op.drop_index('uq_article_keywords_article_keyword', table_name='article_keywords')
    op.drop_index('ix_article_keywords_keyword', table_name='article_keywords')
    op.drop_index('ix_article_keywords_article_id', table_name='article_keywords')
    op.drop_table('article_keywords')
    op.drop_index('uq_article_entities_article_entity_type', table_name='article_entities')
    op.drop_index('ix_article_entities_type', table_name='article_entities')
    op.drop_index('ix_article_entities_entity', table_name='article_entities')
    op.drop_index('ix_article_entities_article_id', table_name='article_entities')
    op.drop_table('article_entities')
    op.drop_index('ix_raw_articles_source_status', table_name='raw_articles')
    op.drop_table('raw_articles')
    op.drop_index(op.f('ix_articles_url'), table_name='articles')
    op.drop_index('ix_articles_source_published', table_name='articles')
    op.drop_index('ix_articles_source_name_published', table_name='articles')
    op.drop_index('ix_articles_search_vector', table_name='articles', postgresql_using='gin')
    op.drop_index('ix_articles_published_id_desc', table_name='articles')
    op.drop_index(op.f('ix_articles_published_at'), table_name='articles')
    op.drop_index(op.f('ix_articles_content_hash'), table_name='articles')
    op.drop_index('ix_articles_category', table_name='articles')
    op.drop_table('articles')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_feed_sources_slug'), table_name='feed_sources')
    op.drop_index(op.f('ix_feed_sources_is_active'), table_name='feed_sources')
    op.drop_table('feed_sources')
    # ### end Alembic commands ###
