"""add_raw_and_failed_article_pipeline

Revision ID: 6a5dbf632264
Revises: e3a2dac764bc
Create Date: 2026-06-10 22:58:09.638020

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6a5dbf632264"
down_revision: Union[str, Sequence[str], None] = "e3a2dac764bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_articles",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("pipeline_run_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=512), nullable=True),
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("fetched_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at_raw", sa.String(length=256), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("transport_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "processing_status",
            sa.Enum(
                "PENDING",
                "NORMALIZED",
                "FAILED",
                name="processingstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("normalization_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"],
            ["pipeline_runs.id"],
            name=op.f("fk_raw_articles_pipeline_run_id_pipeline_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["feed_sources.id"], name=op.f("fk_raw_articles_source_id_feed_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_articles")),
    )
    op.create_index(
        "ix_raw_articles_source_status",
        "raw_articles",
        ["source_id", "processing_status"],
        unique=False,
    )
    op.create_table(
        "failed_articles",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("raw_article_id", sa.Uuid(), nullable=True),
        sa.Column("pipeline_run_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column(
            "failure_stage",
            sa.Enum(
                "COLLECTION",
                "NORMALIZATION",
                "VALIDATION",
                "PERSISTENCE",
                name="failurestage",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("error_type", sa.String(length=256), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("traceback", sa.Text(), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("replayed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"],
            ["pipeline_runs.id"],
            name=op.f("fk_failed_articles_pipeline_run_id_pipeline_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["raw_article_id"],
            ["raw_articles.id"],
            name=op.f("fk_failed_articles_raw_article_id_raw_articles"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["feed_sources.id"],
            name=op.f("fk_failed_articles_source_id_feed_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_failed_articles")),
    )
    op.add_column(
        "articles",
        sa.Column("quality_score", sa.Float(), nullable=True, comment="Quality gate score 0.0-1.0"),
    )
    op.add_column(
        "feed_sources",
        sa.Column(
            "health_status",
            sa.Enum(
                "HEALTHY", "DEGRADED", "BLOCKED", name="sourcehealth", native_enum=False, length=32
            ),
            server_default="HEALTHY",
            nullable=False,
        ),
    )
    op.add_column(
        "feed_sources",
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "feed_sources", sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "feed_sources", sa.Column("last_failed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("feed_sources", sa.Column("error_type", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feed_sources", "error_type")
    op.drop_column("feed_sources", "last_failed_at")
    op.drop_column("feed_sources", "last_success_at")
    op.drop_column("feed_sources", "consecutive_failures")
    op.drop_column("feed_sources", "health_status")
    op.drop_column("articles", "quality_score")
    op.drop_table("failed_articles")
    op.drop_index("ix_raw_articles_source_status", table_name="raw_articles")
    op.drop_table("raw_articles")
    # ### end Alembic commands ###
