"""search_vector_and_indexes

Revision ID: a3e4b8fd6fdd
Revises: 215548651d72
Create Date: 2026-06-11 19:54:11.804470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3e4b8fd6fdd'
down_revision: Union[str, Sequence[str], None] = '215548651d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(summary, '') || ' ' || coalesce(body, ''))", persisted=True), nullable=True))
    op.create_index('ix_articles_published_id_desc', 'articles', [sa.literal_column('published_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_index('ix_articles_search_vector', 'articles', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_articles_source_name_published', 'articles', ['source_name', sa.literal_column('published_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articles_source_name_published', table_name='articles')
    op.drop_index('ix_articles_search_vector', table_name='articles', postgresql_using='gin')
    op.drop_index('ix_articles_published_id_desc', table_name='articles')
    op.drop_column('articles', 'search_vector')
    # ### end Alembic commands ###
