"""add_timezone_hint

Revision ID: e3a2dac764bc
Revises: 38891208f85e
Create Date: 2026-06-10 21:46:19.019414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3a2dac764bc'
down_revision: Union[str, Sequence[str], None] = '38891208f85e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'PARTIAL_SUCCESS', 'FAILED', name='pipelinerunstatus', native_enum=False, length=32), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('failed_sources', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('errors', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_runs'))
    )
    op.alter_column('articles', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Nullable: some RSS feeds omit pubDate. NULLs excluded from time-range queries.',
               existing_nullable=True)
    op.alter_column('articles', 'category',
               existing_type=postgresql.ENUM('MARKETS', 'ECONOMY', 'CORPORATE', 'POLICY', 'COMMODITIES', 'CRYPTO', 'PERSONAL_FINANCE', 'INTERNATIONAL', 'OTHER', name='articlecategory'),
               type_=sa.Enum('MARKETS', 'ECONOMY', 'CORPORATE', 'POLICY', 'COMMODITIES', 'CRYPTO', 'PERSONAL_FINANCE', 'INTERNATIONAL', 'OTHER', name='articlecategory', native_enum=False, length=32),
               existing_nullable=True)
    op.add_column('feed_sources', sa.Column('timezone_hint', sa.String(length=64), server_default='UTC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_sources', 'timezone_hint')
    op.alter_column('articles', 'category',
               existing_type=sa.Enum('MARKETS', 'ECONOMY', 'CORPORATE', 'POLICY', 'COMMODITIES', 'CRYPTO', 'PERSONAL_FINANCE', 'INTERNATIONAL', 'OTHER', name='articlecategory', native_enum=False, length=32),
               type_=postgresql.ENUM('MARKETS', 'ECONOMY', 'CORPORATE', 'POLICY', 'COMMODITIES', 'CRYPTO', 'PERSONAL_FINANCE', 'INTERNATIONAL', 'OTHER', name='articlecategory'),
               existing_nullable=True)
    op.alter_column('articles', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Nullable: some RSS feeds omit pubDate. NULLs excluded from time-range queries.',
               existing_nullable=True)
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
