"""Add pipeline run metrics and source health fields

Revision ID: e48e368856a2
Revises: a3e4b8fd6fdd
Create Date: 2026-06-11 20:43:11.215515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e48e368856a2'
down_revision: Union[str, Sequence[str], None] = 'a3e4b8fd6fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_sources', sa.Column('circuit_breaker_state', sa.Enum('CLOSED', 'OPEN', 'HALF_OPEN', name='circuitbreakerstate', native_enum=False, length=32), server_default='CLOSED', nullable=False))
    op.add_column('feed_sources', sa.Column('success_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('feed_sources', sa.Column('failure_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('feed_sources', sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('feed_sources', sa.Column('last_error', sa.String(length=1024), nullable=True))
    op.add_column('feed_sources', sa.Column('health_score', sa.Float(), server_default='100.0', nullable=False))
    op.drop_column('feed_sources', 'last_failed_at')
    op.drop_column('feed_sources', 'health_status')
    op.drop_column('feed_sources', 'error_type')
    op.add_column('pipeline_runs', sa.Column('duration_ms', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pipeline_runs', sa.Column('articles_ingested', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pipeline_runs', sa.Column('duplicates_detected', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pipeline_runs', sa.Column('failures', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pipeline_runs', sa.Column('source_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pipeline_runs', sa.Column('trigger_type', sa.String(length=64), server_default='MANUAL', nullable=False))
    op.add_column('pipeline_runs', sa.Column('error_summary', sa.Text(), nullable=True))
    op.alter_column('pipeline_runs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('pipeline_runs', 'duplicate_count')
    op.drop_column('pipeline_runs', 'errors')
    op.drop_column('pipeline_runs', 'inserted_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_runs', sa.Column('inserted_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pipeline_runs', sa.Column('errors', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
    op.add_column('pipeline_runs', sa.Column('duplicate_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('pipeline_runs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('pipeline_runs', 'error_summary')
    op.drop_column('pipeline_runs', 'trigger_type')
    op.drop_column('pipeline_runs', 'source_count')
    op.drop_column('pipeline_runs', 'failures')
    op.drop_column('pipeline_runs', 'duplicates_detected')
    op.drop_column('pipeline_runs', 'articles_ingested')
    op.drop_column('pipeline_runs', 'duration_ms')
    op.add_column('feed_sources', sa.Column('error_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('feed_sources', sa.Column('health_status', sa.VARCHAR(length=32), server_default=sa.text("'HEALTHY'::character varying"), autoincrement=False, nullable=False))
    op.add_column('feed_sources', sa.Column('last_failed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('feed_sources', 'health_score')
    op.drop_column('feed_sources', 'last_error')
    op.drop_column('feed_sources', 'last_failure_at')
    op.drop_column('feed_sources', 'failure_count')
    op.drop_column('feed_sources', 'success_count')
    op.drop_column('feed_sources', 'circuit_breaker_state')
    # ### end Alembic commands ###
