"""Add enrichment models

Revision ID: f5e815fc5802
Revises: e48e368856a2
Create Date: 2026-06-11 20:57:56.884418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5e815fc5802'
down_revision: Union[str, Sequence[str], None] = 'e48e368856a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_entities',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('entity', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('extractor_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_entities_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_entities'))
    )
    op.create_index('ix_article_entities_article_id', 'article_entities', ['article_id'], unique=False)
    op.create_index('ix_article_entities_entity', 'article_entities', ['entity'], unique=False)
    op.create_index('ix_article_entities_type', 'article_entities', ['entity_type'], unique=False)
    op.create_index('uq_article_entities_article_entity_type', 'article_entities', ['article_id', 'entity', 'entity_type'], unique=True)
    op.create_table('article_keywords',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_keywords_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_keywords'))
    )
    op.create_index('ix_article_keywords_article_id', 'article_keywords', ['article_id'], unique=False)
    op.create_index('ix_article_keywords_keyword', 'article_keywords', ['keyword'], unique=False)
    op.create_index('uq_article_keywords_article_keyword', 'article_keywords', ['article_id', 'keyword'], unique=True)
    op.create_table('article_sectors',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_sectors_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_sectors'))
    )
    op.create_index('ix_article_sectors_article_id', 'article_sectors', ['article_id'], unique=False)
    op.create_index('ix_article_sectors_sector', 'article_sectors', ['sector'], unique=False)
    op.create_index('uq_article_sectors_article_sector', 'article_sectors', ['article_id', 'sector'], unique=True)
    op.add_column('articles', sa.Column('sentiment_label', sa.String(length=50), nullable=True))
    op.add_column('articles', sa.Column('sentiment_score', sa.Float(), nullable=True))
    op.add_column('articles', sa.Column('generated_summary', sa.Text(), nullable=True))
    op.alter_column('articles', 'sentiment',
               existing_type=postgresql.ENUM('POSITIVE', 'NEGATIVE', 'NEUTRAL', name='sentimentlabel'),
               type_=sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', name='sentimentlabel', native_enum=False, length=32),
               existing_nullable=True)
    op.alter_column('articles', 'feed_source_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_articles_feed_source_id'), table_name='articles')
    op.drop_constraint(op.f('fk_articles_feed_source_id_feed_sources'), 'articles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_articles_feed_source_id_feed_sources'), 'articles', 'feed_sources', ['feed_source_id'], ['id'], ondelete='CASCADE')
    
    # Materialized Views
    op.execute("""
        CREATE MATERIALIZED VIEW hourly_trends_mv AS
        SELECT
            date_trunc('hour', a.published_at) AS time_bucket,
            ae.entity,
            ae.entity_type,
            COUNT(DISTINCT a.id) AS article_count
        FROM articles a
        JOIN article_entities ae ON a.id = ae.article_id
        GROUP BY 1, 2, 3
    """)
    op.execute("CREATE UNIQUE INDEX ix_hourly_trends_mv_unique ON hourly_trends_mv (time_bucket, entity, entity_type)")

    op.execute("""
        CREATE MATERIALIZED VIEW sentiment_summaries_mv AS
        SELECT
            date_trunc('day', a.published_at) AS date_bucket,
            a.sentiment_label,
            COUNT(DISTINCT a.id) AS article_count
        FROM articles a
        WHERE a.sentiment_label IS NOT NULL
        GROUP BY 1, 2
    """)
    op.execute("CREATE UNIQUE INDEX ix_sentiment_summaries_mv_unique ON sentiment_summaries_mv (date_bucket, sentiment_label)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP MATERIALIZED VIEW IF EXISTS sentiment_summaries_mv CASCADE")
    op.execute("DROP MATERIALIZED VIEW IF EXISTS hourly_trends_mv CASCADE")
    
    op.drop_constraint(op.f('fk_articles_feed_source_id_feed_sources'), 'articles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_articles_feed_source_id_feed_sources'), 'articles', 'feed_sources', ['feed_source_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_articles_feed_source_id'), 'articles', ['feed_source_id'], unique=False)
    op.alter_column('articles', 'feed_source_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('articles', 'sentiment',
               existing_type=sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', name='sentimentlabel', native_enum=False, length=32),
               type_=postgresql.ENUM('POSITIVE', 'NEGATIVE', 'NEUTRAL', name='sentimentlabel'),
               existing_nullable=True)
    op.drop_column('articles', 'generated_summary')
    op.drop_column('articles', 'sentiment_score')
    op.drop_column('articles', 'sentiment_label')
    op.drop_index('uq_article_sectors_article_sector', table_name='article_sectors')
    op.drop_index('ix_article_sectors_sector', table_name='article_sectors')
    op.drop_index('ix_article_sectors_article_id', table_name='article_sectors')
    op.drop_table('article_sectors')
    op.drop_index('uq_article_keywords_article_keyword', table_name='article_keywords')
    op.drop_index('ix_article_keywords_keyword', table_name='article_keywords')
    op.drop_index('ix_article_keywords_article_id', table_name='article_keywords')
    op.drop_table('article_keywords')
    op.drop_index('uq_article_entities_article_entity_type', table_name='article_entities')
    op.drop_index('ix_article_entities_type', table_name='article_entities')
    op.drop_index('ix_article_entities_entity', table_name='article_entities')
    op.drop_index('ix_article_entities_article_id', table_name='article_entities')
    op.drop_table('article_entities')
    # ### end Alembic commands ###
