"""Article ORM model — the core entity for collected financial news.

Each row represents a single news article collected, normalized, and
deduplicated by the pipeline. Designed for:
- Fast deduplication via ``content_hash`` and unique ``url``
- Efficient filtering by date, source, and category
- Future ML classification (nullable ``category`` / ``sentiment`` fields)
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, Enum as SAEnum, ForeignKey, Index, String, Text, text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.feed_source import FeedSource


class ArticleCategory(enum.Enum):
    """Broad category for financial news classification.

    Kept intentionally coarse — fine-grained taxonomy belongs in a
    future tagging/label system, not in the primary enum.
    """

    MARKETS = "markets"
    ECONOMY = "economy"
    CORPORATE = "corporate"
    POLICY = "policy"
    COMMODITIES = "commodities"
    CRYPTO = "crypto"
    PERSONAL_FINANCE = "personal_finance"
    INTERNATIONAL = "international"
    OTHER = "other"


class SentimentLabel(enum.Enum):
    """Coarse sentiment label for future ML enrichment."""

    POSITIVE = "positive"
    NEGATIVE = "negative"
    NEUTRAL = "neutral"


class Article(TimestampMixin, Base):
    """A collected and normalized financial news article.

    Attributes:
        id: UUID primary key (generated by PostgreSQL).
        title: Article headline (required, max 512 chars).
        url: Canonical article URL (unique — primary dedup key).
        content_hash: SHA-256 of normalized title+body for content-level dedup.
        summary: Truncated/extracted article summary or description.
        body: Full article text when available.
        author: Byline author name.
        source_name: Human-readable source name snapshotted at collection time.
        image_url: Hero/thumbnail image URL.
        published_at: Original publication timestamp from the source.
        category: Coarse classification (nullable — populated by processor/ML).
        sentiment: Sentiment label (nullable — populated by future ML phase).
        feed_source_id: FK to the FeedSource this article was collected from.
        feed_source: Relationship back to the parent FeedSource.
    """

    __tablename__ = "articles"
    __table_args__ = (
        # Composite index: common query pattern is "recent articles from source X"
        Index("ix_articles_source_published", "feed_source_id", "published_at"),
        # Category index for filtered listing pages
        Index("ix_articles_category", "category"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    title: Mapped[str] = mapped_column(Text, nullable=False)
    url: Mapped[str] = mapped_column(String(4096), unique=True, nullable=False, index=True)
    content_hash: Mapped[str] = mapped_column(
        String(64),
        unique=True,
        nullable=False,
        index=True,
        comment="SHA-256 hex digest of normalized title + body for dedup",
    )
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    body: Mapped[str | None] = mapped_column(Text, nullable=True)
    author: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_name: Mapped[str | None] = mapped_column(Text, nullable=True)
    image_url: Mapped[str | None] = mapped_column(String(2048), nullable=True)

    published_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
        comment="Nullable: some RSS feeds omit pubDate. NULLs excluded from time-range queries.",
    )

    quality_score: Mapped[float | None] = mapped_column(
        nullable=True, comment="Quality gate score 0.0-1.0"
    )

    # --- Classification fields (nullable — populated by processor / future ML) ---
    category: Mapped[ArticleCategory | None] = mapped_column(
        SAEnum(ArticleCategory, native_enum=False, create_constraint=False, length=32),
        nullable=True,
    )
    sentiment: Mapped[SentimentLabel | None] = mapped_column(nullable=True)

    # --- Feed source FK ---
    feed_source_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("feed_sources.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # --- Relationships ---
    feed_source: Mapped["FeedSource | None"] = relationship(  # noqa: F821
        back_populates="articles",
    )
