"""FeedSource ORM model — represents an RSS feed or API endpoint to collect from.

Each FeedSource defines a single collection target (RSS feed URL, API endpoint, etc.).
Articles reference back to their originating feed via a foreign key.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import String, Text, text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin

if TYPE_CHECKING:
    from app.models.article import Article


class SourceType(enum.Enum):
    """Type of news source being collected from."""

    RSS = "rss"
    API = "api"
    SCRAPER = "scraper"


class CircuitBreakerState(enum.Enum):
    """Circuit breaker states for sources."""

    CLOSED = "closed"
    OPEN = "open"
    HALF_OPEN = "half_open"


class FeedSource(TimestampMixin, Base):
    """A configured news feed or API source for collection.

    Attributes:
        id: UUID primary key (generated by PostgreSQL).
        name: Human-readable display name (e.g. "Economic Times - Markets").
        slug: URL-safe unique identifier used in API paths and dedup keys.
        url: The feed URL or API endpoint to collect from.
        source_type: Enum indicating collection strategy (RSS, API, scraper).
        timezone_hint: Timezone name to assist normalizer timestamp parsing.
        is_active: Whether the pipeline should collect from this source.
        description: Optional notes about the feed.
        articles: Relationship to collected articles (lazy-loaded by default).
    """

    __tablename__ = "feed_sources"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    name: Mapped[str] = mapped_column(String(256), nullable=False)
    slug: Mapped[str] = mapped_column(String(128), unique=True, nullable=False, index=True)
    url: Mapped[str] = mapped_column(String(2048), unique=True, nullable=False)
    source_type: Mapped[SourceType] = mapped_column(nullable=False, default=SourceType.RSS)
    timezone_hint: Mapped[str] = mapped_column(String(64), nullable=False, server_default="UTC")
    is_active: Mapped[bool] = mapped_column(nullable=False, default=True, index=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)

    # --- Source Health ---
    from sqlalchemy import DateTime, Float
    from sqlalchemy import Enum as SAEnum

    circuit_breaker_state: Mapped[CircuitBreakerState] = mapped_column(
        SAEnum(CircuitBreakerState, native_enum=False, create_constraint=False, length=32),
        nullable=False,
        server_default="CLOSED",
    )
    success_count: Mapped[int] = mapped_column(nullable=False, server_default="0")
    failure_count: Mapped[int] = mapped_column(nullable=False, server_default="0")
    consecutive_failures: Mapped[int] = mapped_column(nullable=False, server_default="0")
    last_success_at: Mapped["datetime | None"] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    last_failure_at: Mapped["datetime | None"] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    last_error: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    health_score: Mapped[float] = mapped_column(Float, nullable=False, server_default="100.0")

    # --- Relationships ---
    articles: Mapped[list["Article"]] = relationship(  # noqa: F821
        back_populates="feed_source",
        lazy="raise",
    )
